version: '3.8'

services:
  bitcoin:
    image: retropexx/bitcoind:v26.1@sha256:14d3acf5f5d3030631161e37d8f8115f489acf94340cd6bc45328584442603e4
    restart: unless-stopped
    stop_grace_period: 30s
    networks:
      - bitcoin
    ports:
      - "127.0.0.1:8332:8332/tcp"
      - "0.0.0.0:8333:8333/tcp"
    command: >
      -printtoconsole
      -datadir=/app/data
    volumes:
      - "./data/mainnet/bitcoin:/app/data"
      - "./bitcoin-mainnet.conf:/app/data/bitcoin.conf:ro"

  public-pool:
    image: ghcr.io/benjamin-wilson/public-pool:a98ec38
    restart: unless-stopped
    stop_grace_period: 30s
    networks:
      - bitcoin
    ports:
      - "0.0.0.0:3333:3333/tcp"
      - "127.0.0.1:3334:3334/tcp"
    volumes:
      - "./data/mainnet/public-pool:/public-pool/DB"
      - "./public-pool-mainnet.env:/public-pool/.env:ro"
    environment:
      - NODE_ENV=production

networks:
  bitcoin:
